CREATE  database LIBRARY;
USE LIBRARY;
create table E_Book
(  CALLNO VARCHAR(3000),
NAME VARCHAR(3000),
AUTHOR VARCHAR(3000),
PUBLISHER VARCHAR(3000),
QUANTITY INTEGER,
ISSUED INTEGER,
PRIMARY KEY(CALLNO)  );

CREATE TABLE E_LIBRARIAN
(  ID INTEGER auto_increment,
NAME VARCHAR(3000),
PASSWORD VARCHAR(3000),
EMAIL VARCHAR(3000),
MOBILE VARCHAR(20),
PRIMARY KEY(ID)  );

CREATE TABLE  E_ISSUEBOOK
(  CALLNO VARCHAR(3000) NOT NULL,
STUDENTID VARCHAR(3000),
STUDENTNAME VARCHAR(3000),
STUDENTMOBILE VARCHAR(20),
ISSUEDATE DATE,
RETURNSTATUS VARCHAR(3000)  );

